[theme]
primaryColor = "#4318FF"
backgroundColor = "#F4F7FE"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1B2559"
font = "sans serif"

[server]
maxUploadSize = 100
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
